const demoProperties = [
  {
    "id": "1",
    "title": "فيلا دورين ونصف",
    "description": "A charming cottage in the countryside.",
    "propertyType": "Cottage",
    "address": "منطقة الرياض، الرياض، حي السلام، شارع الريف",
    "geoLocation": [34.0522, -118.2437],
    "direction": "شمال",
    "area": [120, 100],
    "regularPrice": 300000,
    "discountPrice": 280000,
    "bathrooms": 2,
    "bedrooms": 3,
    "furnished": true,
    "parking": 1,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user1"
  },
  {
    "id": "2",
    "title": "فيلا دورين ونصف",
    "description": "A sleek and modern flat in the city.",
    "propertyType": "Flat",
    "address": "منطقة مكة المكرمة، مكة المكرمة، حي العزيزية، شارع المدينة",
    "geoLocation": [40.7128, -74.0060],
    "direction": "شرق",
    "area": [90, 80],
    "regularPrice": 450000,
    "discountPrice": 430000,
    "bathrooms": 1,
    "bedrooms": 2,
    "furnished": false,
    "parking": 0,
    "offer": false,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user2"
  },
  {
    "id": "3",
    "title": "فيلا دورين ونصف",
    "description": "A large farm with plenty of land.",
    "propertyType": "Farm",
    "address": "منطقة الرياض، الرياض، حي الملز، شارع الفلاح",
    "geoLocation": [36.7783, -119.4179],
    "direction": "غرب",
    "area": [200, 150],
    "regularPrice": 800000,
    "discountPrice": 780000,
    "bathrooms": 3,
    "bedrooms": 4,
    "furnished": true,
    "parking": 2,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user3"
  },
  {
    "id": "4",
    "title": "فيلا دورين ونصف",
    "description": "A modern office space in the city center.",
    "propertyType": "Office",
    "address": "منطقة الرياض، الرياض، حي الروضة، شارع الملك عبدالعزيز",
    "geoLocation": [37.7749, -122.4194],
    "direction": "جنوب",
    "area": [200, 200],
    "regularPrice": 600000,
    "discountPrice": 590000,
    "bathrooms": 2,
    "bedrooms": 0,
    "furnished": false,
    "parking": 3,
    "offer": false,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user4"
  },
  {
    "id": "5",
    "title": "فيلا دورين ونصف",
    "description": "A luxurious villa with stunning views.",
    "propertyType": "Villa",
    "address": "منطقة الرياض، الرياض، حي الملز، شارع النخيل",
    "geoLocation": [25.7617, -80.1918],
    "direction": "شرق",
    "area": [150, 100],
    "regularPrice": 1200000,
    "discountPrice": 1150000,
    "bathrooms": 4,
    "bedrooms": 5,
    "furnished": true,
    "parking": 2,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user5"
  },
  {
    "id": "6",
    "title": "فيلا دورين ونصف",
    "description": "A compact studio apartment in downtown.",
    "propertyType": "Studio",
    "address": "منطقة مكة المكرمة، مكة المكرمة، حي البحيرة، شارع الأمير مشعل",
    "geoLocation": [34.0522, -118.2437],
    "direction": "شمال",
    "area": [50, 50],
    "regularPrice": 200000,
    "discountPrice": 195000,
    "bathrooms": 1,
    "bedrooms": 0,
    "furnished": false,
    "parking": 1,
    "offer": false,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user6"
  },
  {
    "id": "7",
    "title": "فيلا دورين ونصف",
    "description": "A bustling retail mall in a prime location.",
    "propertyType": "Mall",
    "address": "منطقة تبوك، تبوك، حي الحمراء، شارع التجارة",
    "geoLocation":[39.7392, -104.9903],
    "direction": "جنوب",
    "area": [100, 90],
    "regularPrice": 5000000,
    "discountPrice": 4950000,
    "bathrooms": 10,
    "bedrooms": 0,
    "furnished": true,
    "parking": 100,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user7"
  },
  {
    "id": "8",
    "title": "فيلا دورين ونصف",
    "description": "A large warehouse for storage purposes.",
    "propertyType": "Storage",
    "address": "منطقة حائل، حائل، حي السويدي، شارع الصناعة",
    "geoLocation": [41.8781, -87.6298],
    "direction": "غرب",
    "area": [80, 75],
    "regularPrice": 700000,
    "discountPrice": 690000,
    "bathrooms": 2,
    "bedrooms": 0,
    "furnished": false,
    "parking": 10,
    "offer": false,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user8"
  },
  {
    "id": "9",
    "title": "فيلا دورين ونصف",
    "description": "An open workshop space with high ceilings.",
    "propertyType": "Workshop",
    "address": "منطقة القصيم، القصيم، حي الوادي، شارع الورشة",
    "geoLocation": [47.6062, -122.3321],
    "direction": "شمال",
    "area": [150, 100],
    "regularPrice": 400000,
    "discountPrice": 390000,
    "bathrooms": 1,
    "bedrooms": 0,
    "furnished": false,
    "parking": 5,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user9"
  },
  {
    "id": "10",
    "title": "فيلا دورين ونصف",
    "description": "A magnificent palace with grand architecture.",
    "propertyType": "Cottage",
    "address": "منطقة الرياض، الرياض، حي الملز، شارع القصر",
    "geoLocation": [51.5074, -0.1278],
    "direction": "شرق",
    "area": [150, 140],
    "regularPrice": 20000000,
    "discountPrice": 19500000,
    "bathrooms": 10,
    "bedrooms": 12,
    "furnished": true,
    "parking": 50,
    "offer": true,
    "endDate": "2024-06-06T00:00:00.000Z",
    "imageUrls": "https://i.ibb.co/CBQXcC1/image-1.png",
    "userRef": "user10"
  }
];

export default demoProperties;

